### PR TITLE
Spanish ver

### PR DESCRIPTION
**Pull request by SimpleSenpai12**
So... I translated the `how to get id's` and the README of the repo into spanish :p

### CODE REVIEW

**Comment by SimpleSenpai12** [comment]
NOTE: You may want to create a new branch for the Spanish version, as my translation removes the English text from the files I changed.

**Comment by nerrixDE** [comment]
Yeah @SimpleSenpai12 could you remove the english?

**Review by nerrixDE — CHANGES_REQUESTED** [review]
English removal required, then we can merge it into the new branch 😃

**Comment by SimpleSenpai12** [comment]
Ok!

On Jan 15, 2021, at 8:26 AM, Nerrix <notifications@github.com> wrote:

﻿

@nerrixDE requested changes on this pull request.

English removal required, then we can merge it into the new branch 😃

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nerrixDE_discordid-2Dwiki_pull_5-23pullrequestreview-2D569255964&d=DwMFaQ&c=EHGRkEbb0y4f-dFdKkQ2iQ&r=RUWX0Q-UcoPrKqFyj64KePn-NlgIBwhuHMxwfrQ1JIE&m=f-q911B-pb2gfhgfY5H4fbx63KklEg-n2xeM6gYdTDw&s=H1ehKvD2uhvABMWki-XALyUgGAN7zlZ_3r4oPDRRTnI&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQX3SOEVMN4YQRJXB6P5BQ3S2A67XANCNFSM4WD3GVEQ&d=DwMFaQ&c=EHGRkEbb0y4f-dFdKkQ2iQ&r=RUWX0Q-UcoPrKqFyj64KePn-NlgIBwhuHMxwfrQ1JIE&m=f-q911B-pb2gfhgfY5H4fbx63KklEg-n2xeM6gYdTDw&s=mGQScmG6q4aECJ3d7YbjncwQfvtFYdUXpK2HZTfrrYs&e=>.

The information in this email, including any attachments, is confidential and if you are not the intended recipient be advised that you have received this email in error and any use, dissemination, forwarding, printing or copying of it is strictly prohibited, and may be subject to civil or criminal penalties. If you have received this email in error you should notify the sender by return email and delete the entire communication, including any attachments, from your computer system(s) or storage medium(s). It is the responsibility of the addressee to scan this mail and any attachments for computer viruses or other defects. The sender does not accept liability for any loss or damage of any nature, however caused, which may result directly or indirectly from this email or any file attached. Email sent through the Internet is not secure. Do not use email to send us sensitive information such as credit card numbers, PIN numbers, Social Security Numbers, account numbers or other such information. Please don't print this e-mail unless it is necessary.

**Comment by nerrixDE** [comment]
@SimpleSenpai12 Deleted your comment as it contained email headers and links regarding your email provider which may not should be public

**Comment by nerrixDE** [comment]
This PR seems to be abandoned

**Pull request closed without merging**
